/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  agoric: [
    {
      type: 'autogenerated',
      dirName: 'agoric',
    },
  ],
  algo: [
    {
      type: 'autogenerated',
      dirName: 'algo',
    },
  ],
  cliClipanion: [
    {
      type: 'autogenerated',
      dirName: 'cli/clipanion',
    },
  ],
  cliCommander: [
    {
      type: 'autogenerated',
      dirName: 'cli/commander',
    },
  ],
  cliEnquirer: [
    {
      type: 'autogenerated',
      dirName: 'cli/enquirer',
    },
  ],
  clifastxmlparser: [
    {
      type: 'autogenerated',
      dirName: 'cli/fast-xml-parser',
    },
  ],
  cli: [
    {
      type: 'autogenerated',
      dirName: 'cli',
    },
  ],
  grunt: [
    {
      type: 'autogenerated',
      dirName: 'cli/grunt-docs',
    },
  ],
  listr2: [
    {
      type: 'autogenerated',
      dirName: 'cli/listr2',
    },
  ],
  nodemon: [
    {
      type: 'autogenerated',
      dirName: 'cli/nodemon',
    },
  ],
  pm2: [
    {
      type: 'autogenerated',
      dirName: 'cli/pm2-hive.github.io',
    },
  ],
  tsx: [
    {
      type: 'autogenerated',
      dirName: 'cli/tsx',
    },
  ],
  vuecli: [
    {
      type: 'autogenerated',
      dirName: 'cli/vue-cli',
    },
  ],
  bootstrap: [
    {
      type: 'autogenerated',
      dirName: 'frontend/bootstrap',
    },
  ],
  coreui: [
    {
      type: 'autogenerated',
      dirName: 'frontend/coreui',
    },
  ],
  croner: [
    {
      type: 'autogenerated',
      dirName: 'frontend/croner',
    },
  ],
  denoland: [
    {
      type: 'autogenerated',
      dirName: 'frontend/denoland',
    },
  ],
  ngmocks: [
    {
      type: 'autogenerated',
      dirName: 'frontend/ng-mocks',
    },
  ],
  preact: [
    {
      type: 'autogenerated',
      dirName: 'frontend/preact',
    },
  ],
  yeoman: [
    {
      type: 'autogenerated',
      dirName: 'frontend/yeoman',
    },
  ],
  bilgisayar: [
    {
      type: 'autogenerated',
      dirName: 'bilgisayar',
    },
  ],
  connext: [
    {
      type: 'autogenerated',
      dirName: 'connext',
    },
  ],
  covalent: [
    {
      type: 'autogenerated',
      dirName: 'covalent',
    },
  ],
  camino: [
    {
      type: 'autogenerated',
      dirName: 'camino',
    },
  ],
  agoricdoc: [
    {
      type: 'autogenerated',
      dirName: 'agoric-doc',
    },
  ],
  manta: [
    {
      type: 'autogenerated',
      dirName: 'manta',
    },
  ],
  polygon: [
    {
      type: 'autogenerated',
      dirName: 'polygon',
    },
  ],
  bnbchain: [
    {
      type: 'autogenerated',
      dirName: 'bnb-chain',
    },
  ],

  robonomics: [
    {
      type: 'autogenerated',
      dirName: 'robonomics',
    },
  ],
  rust: [
    {
      type: 'autogenerated',
      dirName: 'rust',
    },
  ],
  solidity: [
    {
      type: 'autogenerated',
      dirName: 'solidity',
    },
  ],
  solona: [
    {
      type: 'autogenerated',
      dirName: 'solona',
    },
  ],
  starknet: [
    {
      type: 'autogenerated',
      dirName: 'starknet',
    },
  ],
  scilla: [
    {
      type: 'autogenerated',
      dirName: 'scilla',
    },
  ],
  pseudo: [
    {
      type: 'autogenerated',
      dirName: 'pseudo',
    },
  ],
  otuzsoru: [
    {
      type: 'autogenerated',
      dirName: 'ogren/otuzsoru',
    },
  ],
  temelblokzincir: [
    {
      type: 'autogenerated',
      dirName: 'ogren/temelblokzincir',
    },
  ],
  agoricbootcamp: [
    {
      type: 'autogenerated',
      dirName: 'bootcamp/agoric',
    },
  ],
  inter: [
    {
      type: 'autogenerated',
      dirName: 'inter',
    },
  ],
  opencv: [
    {
      type: 'autogenerated',
      dirName: 'opencv',
    },
  ],
  gearprotocol: [
    {
      type: 'autogenerated',
      dirName: 'gearprotocol',
    },
  ],
  ton: [
    {
      type: 'autogenerated',
      dirName: 'ton',
    },
  ]




  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;