/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  agoric: [
    {
      type: 'autogenerated',
      dirName: 'agoric',
    },
  ],
  algo: [
    {
      type: 'autogenerated',
      dirName: 'algo',
    },
  ],
  bilgisayar: [
    {
      type: 'autogenerated',
      dirName: 'bilgisayar',
    },
  ],
  connext: [
    {
      type: 'autogenerated',
      dirName: 'connext',
    },
  ],
  covalent: [
    {
      type: 'autogenerated',
      dirName: 'covalent',
    },
  ],
  camino: [
    {
      type: 'autogenerated',
      dirName: 'camino',
    },
  ],
  agoricdoc: [
    {
      type: 'autogenerated',
      dirName: 'agoric-doc',
    },
  ],
  manta: [
    {
      type: 'autogenerated',
      dirName: 'manta',
    },
  ],
  polygon: [
    {
      type: 'autogenerated',
      dirName: 'polygon',
    },
  ],
  robonomics: [
    {
      type: 'autogenerated',
      dirName: 'robonomics',
    },
  ],
  rust: [
    {
      type: 'autogenerated',
      dirName: 'rust',
    },
  ],
  solidity: [
    {
      type: 'autogenerated',
      dirName: 'solidity',
    },
  ],
  solona: [
    {
      type: 'autogenerated',
      dirName: 'solona',
    },
  ],
  starknet: [
    {
      type: 'autogenerated',
      dirName: 'starknet',
    },
  ],
  scilla: [
    {
      type: 'autogenerated',
      dirName: 'scilla',
    },
  ],
  pseudo: [
    {
      type: 'autogenerated',
      dirName: 'pseudo',
    },
  ],
  otuzsoru: [
    {
      type: 'autogenerated',
      dirName: 'ogren/otuzsoru',
    },
  ],
  temelblokzincir: [
    {
      type: 'autogenerated',
      dirName: 'ogren/temelblokzincir',
    },
  ],
  agoricbootcamp: [
    {
      type: 'autogenerated',
      dirName: 'bootcamp/agoric',
    },
  ],
  llama: [
    {
      type: 'autogenerated',
      dirName: 'llama',
    },
  ],
  agoricbootcampchain: [
    {
      type: 'autogenerated',
      dirName: 'bootcamp/agoric-chainboard',
    },
  ],
  yourbookConnext: [
    {
      type: 'autogenerated',
      dirName: 'your-book/connext',
    },
  ],
  yourbookAgoric: [
    {
      type: 'autogenerated',
      dirName: 'your-book/agoric',
    },
  ],
  yourbookMoonbeam: [
    {
      type: 'autogenerated',
      dirName: 'your-book/moonbeam',
    },
  ],
  yourbookCovalentAPI: [
    {
      type: 'autogenerated',
      dirName: 'your-book/covalentapi',
    },
  ],
  yourbookCamino: [
    {
      type: 'autogenerated',
      dirName: 'your-book/camino',
    },
  ],
  inter: [
    {
      type: 'autogenerated',
      dirName: 'inter',
    },
  ],
  opencv: [
    {
      type: 'autogenerated',
      dirName: 'opencv',
    },
  ],
  gearprotocol: [
    {
      type: 'autogenerated',
      dirName: 'gearprotocol',
    },
  ],
  tonv2: [
    {
      type: 'autogenerated',
      dirName: 'tonv2',
    },
  ],
  ton: [
    {
      type: 'autogenerated',
      dirName: 'ton',
    },
  ]




  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;